server:
  port: ${PORT:9000}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    preferIpAddress: true


endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false



logging:
  level:
    com.netflix.discovery: 'OFF'

