server:
  port: ${PORT:8081}

spring:
  cloud:
    kubernetes:
      secrets:
        enabled: true
        enableApi: true
      reload:
        enabled: true
        
store:
  dbUser: ${secret.username:test}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    preferIpAddress: true

management:
  security:
    enabled: false

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

logging:
  level:
    com.netflix.discovery: 'OFF'
    example: 'INFO'
