server:
  port: ${PORT:8082}

        
store:
  dbUser: ${secret.username:test}


management:
  security:
    enabled: false

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

logging:
  level:
    com.netflix.discovery: 'OFF'
    example: 'INFO'
