server:
  port: ${PORT:8082}

        
store:
  dbUser: ${secret.username:test}


management:
  security:
    enabled: false

endpoints:
  actuator:
    path: /mngmt/actuator
  env:
    path: /mngmt/env
  health:
    path: /mngmt/health
  info:
    path: /mngmt/info
  restart:
    enabled: true
  shutdown:
    enabled: true

logging:
  level:
    com.netflix.discovery: 'OFF'
    example: 'INFO'
