server:
  port: ${PORT:8888}

spring:
  application:
     name: configserver
  profiles:
     active: native
     
endpoints:
  actuator:
    path: /mngmt/actuator
  env:
    path: /mngmt/env
  health:
    path: /mngmt/health
  info:
    path: /mngmt/info