my:
  otherprop: myotherval
  property: myvalue
  
configserverdata:
  myconfig: myconfigdata
  
dynamiczuul:
  testConfig: "Test value"
endpoints:
  actuator:
    path: /mngmt/actuator
  env:
    path: /mngmt/env
  health:
    path: /mngmt/health
  info:
    path: /mngmt/info

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    preferIpAddress: true 