apiVersion: v1
kind: Template
labels:
  template: app-springboot-dc-template
metadata:
  name: app-springboot-dc
objects: 
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${APP_NAME}-${SERVICE_NAME}${DEPLOYMENT_TYPE_SUFIX}
  spec:
    replicas: ${NUM_REPLICAS}
    selector:
      name: ${APP_NAME}-${SERVICE_NAME}${DEPLOYMENT_TYPE_SUFIX}
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          name: ${APP_NAME}-${SERVICE_NAME}${DEPLOYMENT_TYPE_SUFIX}
      spec:
        containers:
        - name: ${APP_NAME}-${SERVICE_NAME}${DEPLOYMENT_TYPE_SUFIX}
          resources:
            requests:
              cpu: 250m
              memory: "512Mi"
            limits:
              cpu: '2'
              memory: "1024Mi"
          livenessProbe:
            httpGet:
              path: ${HEALTH_PATH}
              port: ${{PORT}}
              scheme: HTTP   
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: ${HEALTH_PATH}
              port: ${{PORT}}
              scheme: HTTP
            initialDelaySeconds: 20
          env:
            - name: PORT
              value:  "${PORT}"
            - name: SERVICES_PORT
              value:  "${PORT}"
            - name: EUREKA_URI
              value:  "${EUREKA_URI}"
            - name: CONFIG_SERVER_URI
              value:  "${CONFIG_SERVER_URI}"
            - name: APP_ARTIFACT_ID
              value:  "${APP_ARTIFACT_ID}"
            - name: APP_VERSION
              value:  "${APP_VERSION}"
            - name: JAVA_OPTIONS
              value: '-Xms${APP_REQUEST_MEMORY_MI}m -Xmx${APP_LIMIT_MEMORY_MI}m'

    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APP_NAME}-${SERVICE_NAME}
        from:
          kind: ImageStreamTag
          namespace: ${BUILD_NAMESPACE}
          name: ${APP_NAME}-${SERVICE_NAME}:${IMAGE_VERSION}
      type: ImageChange
    - type: ConfigChange
    
parameters:
- name: BUILD_NAMESPACE
  required: true  
- name: SERVICE_NAME
  required: true  
- name: APP_NAME
  required: true
- name: DEPLOYMENT_TYPE_SUFIX
  value: ""
- name: PORT
  required: true
- name: EUREKA_URI
  required: true
- name: CONFIG_SERVER_URI
  required: true  
- name: IMAGE_VERSION
  value: latest
- name: NUM_REPLICAS
  value: "1"
- name: CHECKS_INITIAL_DELAY_SECONDS
  value: "20"
- name: APP_ARTIFACT_ID
  required: true
- name: APP_VERSION
  required: true
- name: APP_REQUEST_MEMORY_MI
  value: "512"
- name: APP_LIMIT_MEMORY_MI
  value: "1024"
- name: HEALTH_PATH
  value: "/health"