apiVersion: v1
kind: Template
labels:
  template: app-springboot-is-template
metadata:
  name: app-springboot-is
objects: 
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ${APP_NAME}-${SERVICE_NAME}
  spec: {}
    
parameters:
- name: SERVICE_NAME
  value: eureka  
- name: APP_NAME
  required: true
  