apiVersion: v1
kind: Template
labels:
  template: app-springboot-dc-template
metadata:
  name: app-springboot-dc
objects: 
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${APP_NAME}-${SERVICE_NAME}
  spec:
    replicas: ${NUM_REPLICAS}
    selector:
      name: ${APP_NAME}-${SERVICE_NAME}
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          name: ${APP_NAME}-${SERVICE_NAME}
      spec:
        containers:
        - name: ${APP_NAME}-${SERVICE_NAME}
          livenessProbe:
            httpGet:
              path: /health
              port: ${{PORT}}
              scheme: HTTP   
            initialDelaySeconds: 10        
          readinessProbe:
            httpGet:
              path: /health
              port: ${{PORT}}
              scheme: HTTP
            initialDelaySeconds: 10
          env:
            - name: PORT
              value:  "${PORT}"
            - name: EUREKA_URI
              value:  "${EUREKA_URI}"
            - name: CONFIG_SERVER_URI
              value:  "${CONFIG_SERVER_URI}"
            - name: APP_ARTIFACT_ID
              value:  "${APP_ARTIFACT_ID}"
            - name: APP_VERSION
              value:  "${APP_VERSION}"

    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APP_NAME}-${SERVICE_NAME}
        from:
          kind: ImageStreamTag
          name: ${APP_NAME}-${SERVICE_NAME}:${IMAGE_VERSION}
      type: ImageChange
    - type: ConfigChange
    
parameters:
- name: SERVICE_NAME
  required: true  
- name: APP_NAME
  value: openshift-sb
- name: PORT
  required: true
- name: EUREKA_URI
  required: true
- name: CONFIG_SERVER_URI
  required: true  
- name: IMAGE_VERSION
  value: latest
- name: NUM_REPLICAS
  value: "1"
- name: APP_ARTIFACT_ID
  required: true
- name: APP_VERSION
  required: true
