apiVersion: v1
kind: Template
labels:
  template: app-springboot-service-template
metadata:
  name: app-springboot-service
objects:
- kind: Service
  apiVersion: v1
  metadata:
    name: "${APP_NAME}-${SERVICE_NAME}"
  spec:
    ports:
    - name: ${APP_NAME}-${SERVICE_NAME}
      protocol: TCP
      port: ${{PORT}}
      targetPort: ${{PORT}}
    selector:
      name: "${APP_NAME}-${SERVICE_NAME}"

parameters:
- name: SERVICE_NAME
  value: eureka  
- name: APP_NAME
  value: openshift-sb
- name: PORT
  required: true
