server:
  port: ${PORT:8761}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0

endpoints:
  actuator:
    path: /mngmt/actuator
  env:
    path: /mngmt/env
  health:
    path: /mngmt/health
  info:
    path: /mngmt/info