---

- hosts: deploy-slave
  tasks:
  vars:
    app_service_name: jwt-spring-security
    app_port: 8765
    source_context_dir: "openshift-sb-{{ app_service_name }}"  
    app_resource_name: "{{ app_name }}-{{ app_service_name }}"  
  vars_files:
    - ./vars/build-vars.yml
  roles:
########################################### 
# - jwt-spring-security
###########################################
    - role: deploy-openshift-template
      template_name: "app-springboot-is-template.yaml"
      template_type: "is"
      resource_name: "{{ app_resource_name }}"
      openshift_extra_params: >
        -p APP_NAME={{ app_name }}
        -p SERVICE_NAME={{ app_service_name }}

    - role: deploy-openshift-template
      template_name: "app-springboot-build-template.yaml"
      template_type: "bc"
      resource_name: "{{ app_resource_name }}"
      openshift_extra_params: >
        -p SOURCE_CONTEXT_DIR=./{{ source_context_dir }}
        -p APP_NAME={{ app_name }}
        -p SERVICE_NAME={{ app_service_name }}
        -p NAMESPACE={{ openshift_project_name }}
        -p BUILD_NAMESPACE={{ build_namespace }}
        -p BUILD_IMAGE={{ build_image }}
        -p GIT_SOURCE_URL={{ git_source_url }}

    - role: deploy-openshift-template
      template_name: "app-springboot-dc-template.yaml"
      template_type: "dc"
      resource_name: "{{ app_resource_name }}"
      openshift_extra_params: >
        -p BUILD_NAMESPACE={{ build_namespace }}
        -p PORT={{ app_port }} 
        -p EUREKA_URI={{ eureka_uri }}
        -p CONFIG_SERVER_URI={{ config_server_uri }}
        -p APP_NAME={{ app_name }}
        -p SERVICE_NAME={{ app_service_name }}
        -p APP_ARTIFACT_ID={{ app_resource_name }}
        -p APP_VERSION={{ app_version }}

    - role: deploy-openshift-template
      template_name: "app-springboot-service-template.yaml"
      template_type: "service"
      resource_name: "{{ app_resource_name }}"
      openshift_extra_params: >
        -p PORT={{ app_port }}
        -p APP_NAME={{ app_name }}
        -p SERVICE_NAME={{ app_service_name }}
    - role: deploy-openshift-template
      template_name: "app-springboot-route-template.yaml"
      template_type: "route"
      resource_name: "{{ app_resource_name }}"
      openshift_extra_params: >
        -p NAMESPACE={{ openshift_project_name }}
        -p ROUTE_HOST_PREFIX={{ app_resource_name }}
        -p APP_NAME={{ app_name }}
        -p SERVICE_NAME={{ app_service_name }}
        -p URL_SUFIX={{ url_sufix }}
