---

- hosts: deploy-slave
  tasks:
  vars_files:
    - ./vars/build-vars.yml
  roles:
########################################### 
# - zuul-server
###########################################
    - role: deploy-openshift-template
      template_name: "app-springboot-is-docker-template.yaml"
      template_type: "is"
      resource_name: "openjdk18-openshift"
      openshift_extra_params: >
        -p APP_NAME=openjdk18
        -p SERVICE_NAME=openshift
        -p IMAGE_NAME=registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:latest
        -p IMAGE_TAG=latest
