# config context path to "/" by setting an empty string
server:
  contextPath:
  port: ${PORT:8080}
  
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    preferIpAddress: true

# JACKSON
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh

endpoints:
  actuator:
    path: /mngmt/actuator
  env:
    path: /mngmt/env
  health:
    path: /mngmt/health
  info:
    path: /mngmt/info